import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import AppLayout from "./components/AppLayout"; //

const Lexend = Lexend_Deca({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kraked - StudyTogether",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the Lexend font, dark background, and white text for a dark theme */}
      <body
        className={`${Lexend.className} antialiased bg-black text-white max-w-7xl mx-auto px-4`}
      >
        <Providers>
          {/* Use the AppLayout component to wrap the entire application content */}
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  );
}
