import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import AppLayout from "./components/AppLayout";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const Lexend = Lexend_Deca({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kraked - StudyTogether",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Lexend.className} antialiased bg-black text-white max-w-7xl md:mx-auto md:px-4`}
      >
        <Providers>
          <AppLayout>
            {children}
            <Analytics />
            <SpeedInsights />
          </AppLayout>
        </Providers>
      </body>
    </html>
  );
}
